- name: "Stop Geth and Ursula Containers if they are running"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:
    - name: Stop Ursula
      become: yes
      docker_container:
        name: ursula
        state: stopped
        image: "{{ nucypher_image | default('nucypher/nucypher:latest') }}"

    - set_fact: restarting_geth=True
    - name: Stop Geth
      become: yes
      docker_container:
        name: geth
        state: stopped
      when: node_is_decentralized is not undefined and node_is_decentralized
