language: python
cache: pip
python:
- '3.5'
- '3.6'
install:
- pip install pipenv --upgrade
- pipenv install --dev --three --skip-lock
before_script:
- wget https://github.com/ethereum/solidity/releases/download/v0.4.23/solc-static-linux -O "${VIRTUAL_ENV}/bin/solc"
- chmod +x "${VIRTUAL_ENV}/bin/solc"
script:
- pipenv run -- pytest --runslow --cov=nucypher -v tests
- codecov