- name: "Rename Ursula configuration files"
  hosts: "{{ 'tag_Role_' + lookup('env', 'NUCYPHER_NETWORK_NAME') + '_ursulas' }}"
  user: ubuntu
  gather_facts: false
  vars:
    old: ~/.local/share/nucypher/Ursula.config
    new: ~/.local/share/nucypher/ursula.config
  pre_tasks:
    - include_vars: "{{ lookup('env', 'ANSIBLE_VARIABLES') }}"
  tasks:
    - name: Check for existing configuration file
      stat: path={{ old }}
      register: configuration_file

    - name: Rename Configuration File (if existing)
      command: mv {{ old }} {{ new }}
      when: configuration_file.stat.exists
