- name: "Setup Remote Worker"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"

- import_playbook: include/setup_user.yml
- import_playbook: include/setup_docker.yml
- import_playbook: include/install_geth.yml
- import_playbook: include/init_worker.yml
- import_playbook: include/run_geth.yml
  when: node_is_decentralized is not undefined and node_is_decentralized
- import_playbook: include/init_ursula.yml
- import_playbook: include/run_ursula.yml
- import_playbook: include/check_running_ursula.yml
- import_playbook: include/backup_ursula_data.yml
