name: 'ğŸ¥¼ Publish Lynx Experimental'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - v*.*.*
      - epic-*

jobs:
  lynx-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a message if 'lynx' label is present
        if: github.event.pull_request.labels.*.name == 'Lynx ğŸ³'
        run: echo "The 'lynx' label is present. Proceeding with Docker build and push operations."

      - name: Print the labels
        run: echo "The labels are ${{ github.event.pull_request.labels }}"

      - name: Call Docker Workflow if Label is Present
        if: github.event.pull_request.labels.*.name == 'Lynx ğŸ³'
        uses: ./.github/workflows/lynx-docker.yml@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
