version: '3'

# runs 8 ursulas, each on a different "host"
# similar to real world conditions

# ex. docker-compose -f 8-federated-ursulas.yml up

services:
  nucypher-dev:
    volumes:
      - ../..:/code
    ports:
      - 11500
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
    image: dev:nucypher
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.0
    container_name: nucypher-dev
  ursula1:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.1 --rest-port 11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.1
    container_name: ursula1
  ursula2:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.2 --rest-port 11500 --teacher 172.28.1.1:11500 
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.2
    container_name: ursula2
  ursula3:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.3 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.3
    container_name: ursula3
  ursula4:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.4 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.4
    container_name: ursula4
  ursula5:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.5 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.5
    container_name: ursula5
  ursula6:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.6 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.6
    container_name: ursula6
  ursula7:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.7 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.7
    container_name: ursula7
  ursula8:
    volumes:
      - ../..:/code
    ports:
      - 11500
    image: dev:nucypher
    depends_on:
      - ursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.28.1.8 --rest-port 11500 --teacher 172.28.1.1:11500
    networks:
      nucypher_net:
        ipv4_address: 172.28.1.8
    container_name: ursula8

networks:
  nucypher_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
